<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DESKTOP-BJ9OE5C" ignored="0" name="RestTest" tests="22" failures="1" timestamp="2021-11-02T16:55:55 IST" time="33.015" errors="0">
  <testcase name="@BeforeClass deleteEmployee" time="1.645" classname="com.restassured.testcases.TC005_Delete_Request">
    <failure type="io.restassured.path.json.exception.JsonPathException" message="Failed to parse the JSON document">
      <![CDATA[io.restassured.path.json.exception.JsonPathException: Failed to parse the JSON document
at io.restassured.path.json.JsonPath$ExceptionCatcher.invoke(JsonPath.java:1002)
at io.restassured.path.json.JsonPath$4.doParseWith(JsonPath.java:967)
at io.restassured.path.json.JsonPath$JsonParser.parseWith(JsonPath.java:1047)
at io.restassured.path.json.JsonPath.get(JsonPath.java:202)
at com.restassured.testcases.TC005_Delete_Request.deleteEmployee(TC005_Delete_Request.java:30)
at java.util.ArrayList.forEach(ArrayList.java:1257)
Caused by: groovy.json.JsonException: Lexing failed on line: 1, column: 1, while reading '<', no possible valid JSON value or punctuation could be recognized.
at groovy.json.JsonLexer.nextToken(JsonLexer.java:86)
at groovy.json.JsonLexer$nextToken.call(Unknown Source)
at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:130)
at io.restassured.internal.path.json.ConfigurableJsonSlurper.parse(ConfigurableJsonSlurper.groovy:97)
at io.restassured.internal.path.json.ConfigurableJsonSlurper$parse.callCurrent(Unknown Source)
at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:51)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:171)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:185)
at io.restassured.internal.path.json.ConfigurableJsonSlurper.parseText(ConfigurableJsonSlurper.groovy:83)
at io.restassured.path.json.JsonPath$4$1.method(JsonPath.java:965)
at io.restassured.path.json.JsonPath$ExceptionCatcher.invoke(JsonPath.java:1000)
... 30 more
... Removed 25 stack frames]]>
    </failure>
  </testcase> <!-- @BeforeClass deleteEmployee -->
  <testcase name="@AfterClass tearDown" time="-1.635852355946E9" classname="com.restassured.testcases.TC005_Delete_Request">
    <skipped/>
  </testcase> <!-- @AfterClass tearDown -->
  <testcase name="checkContentEncoding" time="0.014" classname="com.restassured.testcases.TC001_GET_Request_AllEmployees"/>
  <testcase name="checkContentLenght" time="0.002" classname="com.restassured.testcases.TC001_GET_Request_AllEmployees"/>
  <testcase name="checkContentType" time="0.001" classname="com.restassured.testcases.TC001_GET_Request_AllEmployees"/>
  <testcase name="checkResponse" time="0.06" classname="com.restassured.testcases.TC001_GET_Request_AllEmployees"/>
  <testcase name="checkResponseTime" time="0.005" classname="com.restassured.testcases.TC001_GET_Request_AllEmployees"/>
  <testcase name="checkServerType" time="0.005" classname="com.restassured.testcases.TC001_GET_Request_AllEmployees"/>
  <testcase name="checkStatusCode" time="0.003" classname="com.restassured.testcases.TC001_GET_Request_AllEmployees"/>
  <testcase name="checkStatusLine" time="0.01" classname="com.restassured.testcases.TC001_GET_Request_AllEmployees"/>
  <testcase name="checkContentType" time="0.004" classname="com.restassured.testcases.TC002_GET_Request_SingleEmployee"/>
  <testcase name="checkResponse" time="0.006" classname="com.restassured.testcases.TC002_GET_Request_SingleEmployee">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at com.restassured.testcases.TC002_GET_Request_SingleEmployee.checkResponse(TC002_GET_Request_SingleEmployee.java:37)
at java.util.ArrayList.forEach(ArrayList.java:1257)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- checkResponse -->
  <testcase name="checkResponseTime" time="0.002" classname="com.restassured.testcases.TC002_GET_Request_SingleEmployee"/>
  <testcase name="checkServerType" time="0.002" classname="com.restassured.testcases.TC002_GET_Request_SingleEmployee"/>
  <testcase name="checkStatusCode" time="0.002" classname="com.restassured.testcases.TC002_GET_Request_SingleEmployee"/>
  <testcase name="checkStatusLine" time="0.001" classname="com.restassured.testcases.TC002_GET_Request_SingleEmployee"/>
  <testcase name="checkResponse" time="0.003" classname="com.restassured.testcases.TC003_Post_Request_EmployeeCreation"/>
  <testcase name="checkResponseTime" time="0.003" classname="com.restassured.testcases.TC003_Post_Request_EmployeeCreation"/>
  <testcase name="checkStatusCode" time="0.004" classname="com.restassured.testcases.TC003_Post_Request_EmployeeCreation"/>
  <testcase name="checkResponse" time="0.003" classname="com.restassured.testcases.TC004_Put_Request_EmployeeDetailsUpdation"/>
  <testcase name="checkResponseTime" time="0.003" classname="com.restassured.testcases.TC004_Put_Request_EmployeeDetailsUpdation"/>
  <testcase name="checkStatusCode" time="0.004" classname="com.restassured.testcases.TC004_Put_Request_EmployeeDetailsUpdation"/>
  <testcase name="checkResponse" time="0.0" classname="com.restassured.testcases.TC005_Delete_Request">
    <skipped/>
  </testcase> <!-- checkResponse -->
  <testcase name="checkStatusCode" time="0.0" classname="com.restassured.testcases.TC005_Delete_Request">
    <skipped/>
  </testcase> <!-- checkStatusCode -->
</testsuite> <!-- RestTest -->
